import Foundation

public enum DemoData {
    /// Fictional conversations. `imagePaths` are local demo pictures generated by the app (never real photos).
    public static func conversations(now: Date = Date(), imagePaths: [String] = []) -> [Conversation] {
        typealias Entry = (text: String, fromMe: Bool, image: Int?)
        func text(_ value: String, _ fromMe: Bool) -> Entry { (value, fromMe, nil) }
        func photo(_ index: Int, _ fromMe: Bool, caption: String = "") -> Entry { (caption, fromMe, index) }
        let examples: [(String, [String], [Entry], Int)] = [
            ("Alex Morgan", ["alex@example.test"], [text("Are we still on for coffee tomorrow?", false), text("Absolutely. The place on Spring Street?", true), text("Perfect. 10:30 works for me ☕", false), text("See you there!", true), text("Also, sending you that playlist tonight.", false)], 1),
            ("Weekend crew", ["mia@example.test", "jules@example.test", "sam@example.test"], [text("Small cabin. Big weekend.", false), photo(0, false), text("I'm in. Who's driving?", true), text("I can take three people 🚗", false), text("I'll bring breakfast stuff.", true), text("Let's leave Friday around 5?", false)], 2),
            ("Jamie Chen", ["jamie@example.test"], [text("The new mockups are looking great.", false), photo(1, true, caption: "Simplified the navigation"), text("Much easier to follow now.", false), text("https://www.apple.com/macos/", true), text("I'll send the final version this afternoon.", true), text("Amazing. No rush — take your time.", false)], 0),
            ("Mom", ["mom@example.test"], [text("How's your week going?", false), text("Good! Busy, but good.", true), text("Don't forget to eat a real lunch 😊", false), text("Already on it. Are we doing dinner Sunday?", true), text("Of course. Your favorite pasta.", false)], 0),
            ("Sam Rivera", ["sam@example.test"], [text("Found a new hiking trail for us.", false), text("Send me the details!", true), text("Great views. Only about 4 miles. https://en.wikipedia.org/wiki/Hiking", false)], 1),
            ("Design team", ["riley@example.test", "taylor@example.test"], [text("Quick review at 2?", false), text("Works for me.", true), text("I'll share the board beforehand.", false)], 0),
            ("Taylor Brooks", ["taylor@example.test"], [text("That restaurant was so good.", false), text("Already thinking about going back.", true)], 0),
            ("Riley Park", ["riley@example.test"], [text("Did you finish the book?", false), text("Last chapter tonight!", true)], 0)
        ]
        // Fictional replies ("conversation-message" → the message answered), edits and reactions.
        let replies: [String: Int] = ["1-3": 2, "3-4": 3]
        let edited: Set<String> = ["4-2"]
        let reactions: [Int: [(target: Int, kind: ReactionEvent.Kind, actor: String?)]] = [
            0: [(2, .love, nil), (3, .like, "alex@example.test")],
            1: [(5, .like, nil), (5, .like, "jules@example.test"), (3, .laugh, "sam@example.test")],
            3: [(4, .love, nil)],
        ]
        return examples.enumerated().map { offset, example in
            let messages = example.2.enumerated().compactMap { (index, entry) -> Message? in
                var attachments: [Attachment] = []
                if let image = entry.image {
                    guard imagePaths.indices.contains(image) else { return nil }
                    let path = imagePaths[image]
                    attachments = [Attachment(id: "demo-attachment-\(offset)-\(index)", path: path,
                        name: (path as NSString).lastPathComponent, mimeType: "image/png", uti: "public.png",
                        pixelWidth: image == 0 ? 1200 : 900, pixelHeight: image == 0 ? 800 : 1100)]
                }
                let date = now.addingTimeInterval(Double(-1800 - offset * 600 + index * 240))
                let key = "\(offset)-\(index)"
                return Message(id: "demo-\(key)", text: entry.text, date: date, isFromMe: entry.fromMe,
                    sender: example.1.first, attachments: attachments, isDelivered: entry.fromMe,
                    guid: "demo-\(key)", replyToGUID: replies[key].map { "demo-\(offset)-\($0)" },
                    dateEdited: edited.contains(key) ? date.addingTimeInterval(60) : nil)
            }
            let events = (reactions[offset] ?? []).enumerated().compactMap { (position, reaction) -> ReactionEvent? in
                guard let target = messages.first(where: { $0.id == "demo-\(offset)-\(reaction.target)" }) else { return nil }
                return ReactionEvent(id: "demo-reaction-\(offset)-\(position)", date: target.date.addingTimeInterval(30 + Double(position)),
                    isFromMe: reaction.actor == nil, actor: reaction.actor, targetGUID: target.guid ?? target.id, targetPart: nil,
                    kind: reaction.kind, isRemoval: false)
            }
            return Conversation(id: "demo-\(offset)", name: example.0, participants: example.1,
                preview: messages.last?.text ?? "", lastActivity: messages.last?.date ?? now,
                unreadCount: example.3, messages: messages, reactions: events)
        }
    }
}
